In [1]:
import numpy as np


In [4]:
# creating an array

arr = np.array([1,2,3,4])
print("1D araay: ", arr)


arr_2D = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2D)

1D araay:  [1 2 3 4]
2D array:  [[1 2 3]
 [4 5 6]]


### LIST VS NumPy array

In [6]:
my_list = [1,2,3]

print("Python list multiplication", my_list * 2)


np_array = np.array([1,2,3]) #element wise multiplcation
print("Python np array multiplication", np_array * 2)


# to check the effiency who will get execute first
import time 
start = time.time()
my_list = [i * 2 for i in range (1000000)]
print("\n list operation time: " , time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n np array operation time: " , time.time() - start)


Python list multiplication [1, 2, 3, 1, 2, 3]
Python np array multiplication [2 4 6]

 list operation time:  0.09970641136169434

 np array operation time:  0.007585287094116211


creating array from scratch

In [20]:
zeros = np.zeros((3,4)) # 3 rows 4 column
print("zeros array \n", zeros)


ones = np.ones((2,3))
print("ones array \n", ones)

# 

full = np.full((2,3),8) 
print("full array \n", full)

# random is a class not a method and will have another 

random = np.random.random((2,3))
print("random \n", random)

# start, stop, step , data type
sequence = np.arange(0, 10,2, float)
print("sequence \n", sequence)

zeros array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array 
 [[8 8 8]
 [8 8 8]]
random 
 [[0.78037304 0.55289989 0.7272817 ]
 [0.31067658 0.08310836 0.78736215]]
sequence 
 [0. 2. 4. 6. 8.]


### Vector , Matrix and Tensor

In [ ]:
vector = np.array([1,2,3]) #1D array
print("vector", vector)

matrix = np.array([[1,2,3],[4,5,6]]) #2D array
print("matrix", matrix)


 #3D or higher dimentional array
tensor = np.array([
                  [[1,2,4],[3,4,5]],
                  [[5,6,7],[8,9,10]]
                ])

print("tensor", tensor)

vector [1 2 3]
matrix [[1 2 3]
 [4 5 6]]
tensor [[[ 1  2  4]
  [ 3  4  5]]

 [[ 5  6  7]
  [ 8  9 10]]]


#### Array Properties


In [26]:
arr = np.array([[1,2,3],
                [4,5,6]
                ])


print("shape of array", arr.shape)
print("dimension" , arr.ndim)
print("size", arr.size)
print("datatype", arr.dtype)

shape of array (2, 3)
dimension 2
size 6
datatype int64


### Array Reshaping

In [31]:
array = np.arange(12)
print("original array : " , array)

reshaped_array = array.reshape((3,4)) # convert to 3 x 4 matric
print("reshaped array", reshaped_array)


flattened = reshaped_array.flatten()
print("flattend array", flattened) # returns copy of the array

# important
# returns view instead of copy (returns orignal array)
raveled = reshaped_array.ravel()
print("raveled", raveled)

# transpose

transpose = reshaped_array.T
print("transpose array", transpose)

original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend array [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Numpy Array operations

In [4]:
# indexing and slicing

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8, 9, 10])
print("basic slicing", arr[2: 7])

print("with step", arr[1:8:2])

print("negative indexing", arr[-1:-5: -1])


basic slicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing [10  9  8  7]


In [9]:
# 2d array

array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element: ", array_2D[1,2])

specific element:  6
