# Practice Questions

### Basic

In [1]:
import numpy as np

In [39]:
# create array 1 to 20
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
# create 3 x 3 zero matrix

np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# find shape, size, dtype

# shape
arr.shape

# size
arr.size

# dtype
arr.dtype

dtype('int64')

In [20]:
# convert list - array

my_list = [1,2,3,4,5]
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

### Indexing

In [28]:
# Get even numbers only

even_arr = arr[arr % 2 == 0]
even_arr


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# replace negative with 0
arr[arr < 0] = 0
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
# extract first 5 elements

arr[0:5]

array([0, 0, 0, 0, 0])

In [42]:
# fancy indexing 

arr[[1,5]]

array([1, 5])

### Reshape

In [45]:
# reshape (12,) → (3,4)

arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
array = arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
arr = np.array([[1,2],[3,4]])

flatten_array = arr.flatten()
flatten_array

array([1, 2, 3, 4])

In [56]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
arr.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4]])

### Stats

In [65]:
# mean, median, std, var

arr.mean()
np.median(arr)
np.std(arr)
np.var(arr)

np.float64(1.25)

In [68]:
# percentiles (25, 50, 90)

np.percentile(arr, 25)

np.float64(1.75)

In [69]:
# np.percentile(arr, 50)

np.percentile(arr, 50)

np.float64(2.5)

In [70]:
# np.percentile(90)

np.percentile(arr, 90)

np.float64(3.7)