# NumPy

# Q) What is NumPy?

- Numpy is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. It is widely used in scientific computing, data analysis and machine learning due to its performance and ease of use. Numpy allows for fasr operations on arrays, making it an essential tool for numerical computations in Python

#### Num - Numerical , py - Python


Numpy is 10-100 times faster than regular Python lists for numerical operations, making it a crutial library for data scientists and researchers working with large datasets and complex mathematical computations


In [4]:
import numpy as np

print(np.__version__)

2.4.6


2) Arrays, Shape, Rank, amd Data Type

The most important NumPy habit is to always know:
- shape: how many values exist along each axis
- rank/ndim: how many axes the array has
- dtype: how values are stored in memory

These 3 details affect correctness, speed and memory usage.

In [ ]:
# 1D array

vector = np.array([10,20,30,40,50])

# 2D array often referred to as a matrix, represents rows and columns
table = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

#### 1D

In [8]:
print("1D array (vector):", vector)
#shape of the vector
print(np.shape(vector))

# dimension of the vector
print(np.ndim(vector))

# data type
print(vector.dtype)


1D array (vector): [10 20 30 40 50]
(5,)
1
int64


#### 2D array

In [6]:
print("2D array", table)
# shape of the table
print("shape", np.shape(table))

# dimension of the table
print(np.ndim(table))

2D array [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape (3, 3)
2


inside numpy - we have many packages

In [ ]:
# Modern Numpy recommends default_rng for random number generation. It is more flexible and has better statistical properties than the older np.random functions.
rng = np.random.default_rng(seed=0)

#default_rng - default random number generator
#seed - a fixed value to ensure reproducibility of random numbers
#seed value can be any integer between 0 and 2**32 -1 (inclusive). It is used to initialize the random number generator, ensuring that the same sequence of random numbers is generated each time the code is run with the same seed.
# common seed values are 0, 42, 123, 999, etc. You can choose any integer value as a seed.
random_vector = rng.random(5)
print("random number", random_vector)



random number [0.63696169 0.26978671 0.04097352 0.01652764 0.81327024]


3) Creating Arrays Used in Real Workflows



In [13]:
zeros = np.zeros((3,4))
print("zeros\n", zeros)

ones = np.ones((2,3))
print("ones\n", ones)

identity = np.eye(5)
print("identity\n", identity)

steps = np.arange(0,10,2)
print("steps\n", steps)

grid = np.linspace(0,1,6)
print("grid\n", grid)

random_matrix = rng.normal(0,1,(3,3))
print("random_matrix\n", random_matrix)

zeros
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones
 [[1. 1. 1.]
 [1. 1. 1.]]
identity
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
steps
 [0 2 4 6 8]
grid
 [0.  0.2 0.4 0.6 0.8 1. ]
random_matrix
 [[ 0.35151007  0.90347018  0.0940123 ]
 [-0.74349925 -0.92172538 -0.45772583]
 [ 0.22019512 -1.00961818 -0.20917557]]


4) Indexing, Slicing, and Views

Slicing usually returns a view, not a copy, A view shares memory with the original array. This is fast, but it means edits can affect the souce array.

In [23]:
x = np.arange(12).reshape(3,4)
print("original array: \n", x)

original array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Select one row: (1st row)
print("\n first row\n:" , x[0])


 second row
: [0 1 2 3]


In [18]:
# selecting 1 column (2nd column)
print("\n second column\n:", x[:, 2])


 second column
: [ 2  6 10]


In [19]:
# select a submatrix: rows 0 and 1, columns 1 and 2

sub = x[:2, 1:3]
print("submatrix \n", sub)

submatrix 
 [[1 2]
 [5 6]]


In [21]:
# because sub is a view, this edir changes x too
sub[0,0] = 999
print("original x\n", x)

original x
 [[  0 999   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


#### Deep Copy

#### since when we cahnge anything it will get changed in both original and the view to avoid that we use Deep copy

In [24]:
# since when we cahnge anything it will get changed in both original and the view to avoid that we use Deep copy

# use .copy() when you need independent data

safe_sub = x[:2, 1:3].copy()
print("\n safe submatrix copy before edit: \n", safe_sub)
safe_sub[0,0] = -1
print("\n safe submatrix copy after edit:\n", safe_sub)
print("\n original array\n", x)


 safe submatrix copy before edit: 
 [[1 2]
 [5 6]]

 safe submatrix copy after edit:
 [[-1  2]
 [ 5  6]]

 original array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


5) Boolean Masks and conditional Selection

- Boolean masks make it possible to filter and edit arrats without explicit loops. This is one of the most common array-processing patterns.

In [25]:
scores = np.array([48,76,92,35,68,88,59])
print("original array\n", scores)

original array
 [48 76 92 35 68 88 59]


In [26]:
# build the condition for values that meet a threshold.

passed = scores >= 60
print("masked", passed)
print("selected scores", scores[passed])

masked [False  True  True False  True  True False]
selected scores [76 92 68 88]


In [27]:
scores = np.array([48,76,92,35,68,88,59])

# np.where chooses values element by element

labels = np.where(scores >= 60, "review-later", "needs-attention")
print("Labels: \n" , labels)

Labels: 
 ['needs-attention' 'review-later' 'review-later' 'needs-attention'
 'review-later' 'review-later' 'needs-attention']


#### Clip

In [28]:
scores = np.array([48,76,92,35,68,88,59])

# Clip extreme values to a fixed range
# This is common when preventing outliers from dominating downstream calculations.

clipped = np.clip(scores, 50, 90)
print("clipped: ", clipped)



clipped:  [50 76 90 50 68 88 59]


6) Vectorization: replacing Loops with Array expressions

- vectorization means expressing operations over whole arrays at once. It usually shorter, clearer, and faster than manual Python loops because NumPy does the heavy work in optimized complied code.

In [1]:
values = rng.normal(loc=100, scale=15, size=10_00)
# loc - mean of the distribution, scale - standard deviation, size - number of samples
# Loop style: correct, but slower and more verbose for large arrays

centered_loop = []
mean_value = values.mean()
for value in values:
    centered_loop.append(value - mean_value)
centered_loop = np.array(centered_loop)

# vectorised style: subtract one scalar from every element
centered_vectorized = values - values.mean()

#allclose is safer than exact equality for floating-point values
print("same result:", np.allclose(centered_loop, centered_vectorized))
print("mean after centering", centered_vectorized.mean().round(10))

NameError: name 'rng' is not defined

#### Broadcasting: Shape- Aware Arithmetic

- broadcating lets NumPy combine arrays with different, but compatible, shapes. This is essential for column-wise scaling, row-wise offsets, batch operations, and tensor-style calculations.

In [5]:
x = np.array([
    [170,65,23],
    [182,82,31],
    [160,52,28],
    [175,74,35],
], dtype=float)

print("original data:\n", x)


column_means = x.mean(axis=0)
column_stds = x.std(axis=0)

x_scaled = (x - column_means) / column_stds

print("column mean: ", column_means)
print("column stds: ", column_stds)
print("\n scaled data: \n", x_scaled.round(3))
print("\n scaled column means: ", x_scaled.mean(axis=0).round(10))
print("\n scaled column stds: ", x_scaled.std(axis=0).round(10))

original data:
 [[170.  65.  23.]
 [182.  82.  31.]
 [160.  52.  28.]
 [175.  74.  35.]]
column mean:  [171.75  68.25  29.25]
column stds:  [ 8.01171018 11.14394454  4.38035387]

 scaled data: 
 [[-0.218 -0.292 -1.427]
 [ 1.279  1.234  0.4  ]
 [-1.467 -1.458 -0.285]
 [ 0.406  0.516  1.313]]

 scaled column means:  [0. 0. 0.]

 scaled column stds:  [1. 1. 1.]


#### Reshaping and axis discipline

- Shape mistakes are among the most common causes of numerical bugs. Learn to reshape intentionally and use keepdims=True when a reduced result must still broadcast cleanly.


In [8]:
a = np.arange(24)
print("original array: \n", a)

# reshape without changing data order
batch = a.reshape(2,3,4)

# sum over the last axis, keepdims=true preserves a singleton axis.
row_sums = batch.sum(axis=1, keepdims=True)
print("rows sums shape:", row_sums.shape)

# because row_sums has shape (2,3,1) it broadcasts across the last axis.
normalized_rows = batch / np.where(row_sums == 0, 1, row_sums)
print("\n first matrix row-normalized: \n", normalized_rows[0])

# add a new axis explicitly when needed.
column_vector = np.arange(3)[: , None]
row_vector = np.arange(4)[None, :]
print("\n outer-style sum: \n", column_vector + row_vector)

original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
rows sums shape: (2, 1, 4)

 first matrix row-normalized: 
 [[0.         0.06666667 0.11111111 0.14285714]
 [0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.6        0.55555556 0.52380952]]

 outer-style sum: 
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


#### Aggregations and Descriptive Statistics
- Aggregations summarize arrays along chosen axes. in tabular data, axis=0 usuall summarizes columns, while axis=1 summarizes rows

In [9]:
data = rng.normal(loc=[50,100,500], scale=[5,20,80], size=(8,3))
print(data)

NameError: name 'rng' is not defined

#### Handling Missing and Invalid Values

- Real arrays often contains missing or invalid values. NumPy represents missing floating-point values with np.nan. Use nan-aware functions when appropriate.

In [ ]:
readings =  np.array([
    [10.0, 12.0, np.nan],
    [11.0, np.nan, 15.0],
    [9.0, 13.0, 14.0]
])

print("raw reading \n", readings)

#standard mean returns nan if any value in the slice is nan
print("\n standard column mean: ", readings.mean(axis=0))

#nanmean ignores nan values.
col_means = np.nanmean(readings, axis=0)
print("nan aware column mean", col_means)

# replace missing values with the matching column mean
imputed = np.where(np.isnan(readings), col_means, readings)
print("\n inputed readings: \n", imputed)

# detect finite values. this catches nan, +inf, and -int
print("\n all values finit after imputation: ", np.isfinite(imputed).all())


raw reading 
 [[10. 12. nan]
 [11. nan 15.]
 [ 9. 13. 14.]]

 standard column mean:  [10. nan nan]
nan aware column mean [10.  12.5 14.5]

 inputed readings: 
 [[10.  12.  14.5]
 [11.  12.5 15. ]
 [ 9.  13.  14. ]]

 all vales finit after imputation:  True


### Sorting, ranking, Top-k Selection

- Full sorting is useful, but sometimes you only need the largest or smallest few values. argpartition can be more efficient for top-k style selection

In [12]:
relevance = rng.uniform(0,1, size=12)
print("relevance scores: ", relevance.round(3))
k = 4

# argsort returns indices that would sort the array
sorted_indices = np.argsort(relevance)[::-1]
print("scores", relevance.round(3))
print("top indices by full sort: ", sorted_indices[:k])

NameError: name 'rng' is not defined